# Generated by Django 4.2.16 on 2026-02-26

import decimal
from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    """Initial migration for transaction domain models."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name="categories", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("type", models.CharField(choices=[("income", "Income"), ("expense", "Expense")], max_length=10)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="transactions", to="transactions.category")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField()),
                ("total_income", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("total_expense", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("savings", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="monthly_summaries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("user", "month")},
            },
        ),
    ]
