# Generated by Django 4.2.16 on 2026-02-26

from django.db import migrations


GLOBAL_CATEGORY_NAMES = [
    "Food",
    "Transport",
    "Housing",
    "Health",
    "Entertainment",
    "Shopping",
    "Utilities",
    "Salary",
    "Other",
]


def seed_categories(apps, schema_editor):
    """Insert default global categories."""
    Category = apps.get_model("transactions", "Category")
    for name in GLOBAL_CATEGORY_NAMES:
        Category.objects.get_or_create(name=name, user=None)


def remove_categories(apps, schema_editor):
    """Delete seeded global categories."""
    Category = apps.get_model("transactions", "Category")
    Category.objects.filter(user=None, name__in=GLOBAL_CATEGORY_NAMES).delete()


class Migration(migrations.Migration):
    """Seed default global categories."""

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
