# Generated by Django 4.2.16 on 2026-03-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget'),
        ('transactions', '0003_savings_goal'),
    ]

    operations = [
    ]
